import { Foundation, Pet } from './types';

export const FOUNDATIONS: Foundation[] = [
  {
    id: 'elephant-nature-park',
    name: 'Elephant Nature Park',
    location: 'Chiang Mai',
    verifiedNo: 'TH-5510-101',
    description: 'Find sanctuaries across Thailand that need your support.',
    mission: 'At Elephant Nature Park, our mission is to rescue, rehabilitate, and provide a safe sanctuary for gentle giants and wildlife in Northern Thailand. We provide an environment where they can live free from exploitation, supported by volunteers and conscious travelers globally.',
    animalTypes: ['Wildlife'],
    bannerImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDXN5934uOj7D7OjTCE9JUEOU9lp1BFusOnUmA-kLFBhYFr1l2vWDJ04sjFr1wsi575OXJfVzwqtZmtAUzC73PwItYCKy4TWdcShP6fPohadV3vylgKOQqAoZuZ-8WztF9I6d6_L2m28qh-326fMqpC68HKZp1MYrFEIRSt9X6-ISwyLMrJ2J2ZiV9Rk6KAus0_OW1V0JjpjvfF7fsDIduxTHmUjakO-zo3wVydqgKQMZVnHiynRmwfSrWQuEE00ANoXmBWEoZraJc',
    thumbnailImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDXN5934uOj7D7OjTCE9JUEOU9lp1BFusOnUmA-kLFBhYFr1l2vWDJ04sjFr1wsi575OXJfVzwqtZmtAUzC73PwItYCKy4TWdcShP6fPohadV3vylgKOQqAoZuZ-8WztF9I6d6_L2m28qh-326fMqpC68HKZp1MYrFEIRSt9X6-ISwyLMrJ2J2ZiV9Rk6KAus0_OW1V0JjpjvfF7fsDIduxTHmUjakO-zo3wVydqgKQMZVnHiynRmwfSrWQuEE00ANoXmBWEoZraJc',
    urgent: true,
    coords: { x: 30, y: 20, name: 'Chiang Mai' }
  },
  {
    id: 'soi-dog-foundation',
    name: 'Soi Dog Foundation',
    location: 'Phuket',
    verifiedNo: 'TH-9982-445',
    description: 'Providing sanctuary and rehabilitation for street dogs in Northern Thailand & Southern shelters.',
    mission: 'Soi Dog Foundation helps the homeless, neglected and abused dogs and cats of Thailand. Our aim is to provide a humane and sustainable solution to managing the stray animal population through large-scale sterilization, rescue, and adoption.',
    animalTypes: ['Dogs', 'Cats'],
    bannerImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD61lJ97QUvcfM6zPiGesVKomlY_eqe4yFFZFjQpSLJ0O1zdmEU82AfOLexXT9FVjM3VPK3aWrn2UgCpD42zhSeBoviEDBllwlRJAzPf5vnPvgCQ7PccCUWwtTLaLJWgZ58dGuf35xvbTa5GJiiXQTUrvmNdWBYWqRm7j3fyrRWk9UBYKimgCBStPse_XcsYI1km7mEDIjIYwzE9Ji6i0Uk9Bi8bwuUDNZoDh70mczWrGEgZcdvYQAfFNIhAvQCXar7Sae3JWnwsg8',
    thumbnailImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA2aGmy2aXSts-QNVzMGXy-lYu2ISwjnPFVnAZOZxl82RMLSIMO8anoJW6W7sMveNSurPyBwZMCG3ykFQW4g4kMPtllPrZix98KCQg6tL7wFqDZ_TFZkyYEV3B1unynwEY0Q6Ysyalie9dtYapvLJphyAdZk34-8U25GkNMjojCF2ujMl93YXQ_hNOyzzE6bOfZWUxFxHlPNIAUbBLPRATOkJJ-Q6JKQVe4ZWv3w05cacWmsSRpxMJz78guKvNo5HSbVcUzF8wSyWc',
    urgent: false,
    coords: { x: 35, y: 80, name: 'Phuket' }
  },
  {
    id: 'paws-bangkok',
    name: 'PAWS Bangkok',
    location: 'Bangkok',
    verifiedNo: 'TH-2244-098',
    description: 'Find sanctuaries across Thailand that need your support.',
    mission: 'PAWS Bangkok provides spay/neuter services, medical care, adoption matching, and community education to improve animal welfare in the Bangkok area. We focus on vulnerable cats and street dogs needing intermediate clinic care.',
    animalTypes: ['Cats', 'Dogs'],
    bannerImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC4vc9jr1B5BIuYV7g2AxjZjx4EyMVlVlbKrHVuhyYrtonSuTAzlHOAM3C9IRXHx51Odtec9JwJjhomtsKYoO1v10VSm0FSzNuZvD5EubO252ioj_ctuUFnc0eKVHvL4HzP0oA0o6K0k84xVNsvHGtZzdS8PI6piYO88JjGCdJoodltf1nvetQgPZulBWzK7-AQfUcdMlQYxTn-iRQDWzKVO3xKbKIL4uK2bHHGXtjCflZicahSms7zpEkZJyRtN2qH2l83RA1SvzY',
    thumbnailImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCxJPSJEtHBfq6qZPDd8EE1BJwysQ7qT8b_JlJNnVOUoqB0RJ8VglshvpWznnOm1YMj7GPXsrRAz_kfNSvDQR3E781THATYGB0gLjDCm4p16aAQg85bNK90ieU6HyO0OJDUGf4UOiiEXXH99YMsFIW_-qWwHxaqzgftBbGvc3dOAeVmI1Ga7v6NErPpHD_kclKoGQNZEoTGqaZLUPe1quto9U8Cswk-EOvZ_JVzKrhKj6qhOebjVGhv99Fat1b1f1OoyOAbqy3G_YQ',
    urgent: false,
    coords: { x: 45, y: 50, name: 'Bangkok' }
  },
  {
    id: 'happy-tails-haven',
    name: 'Happy Tails Haven',
    location: 'Chiang Mai',
    verifiedNo: 'TH-9982-445',
    description: 'Providing sanctuary and rehabilitation for street dogs in Northern Thailand.',
    mission: 'At Happy Tails Haven, our mission is to rescue, rehabilitate, and rehome vulnerable street dogs. We believe every animal deserves a chance at a life free from suffering. We provide medical care, nutritious food, and behavioral training in a warm, cage-free environment, preparing them for their forever homes.',
    animalTypes: ['Dogs'],
    bannerImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD61lJ97QUvcfM6zPiGesVKomlY_eqe4yFFZFjQpSLJ0O1zdmEU82AfOLexXT9FVjM3VPK3aWrn2UgCpD42zhSeBoviEDBllwlRJAzPf5vnPvgCQ7PccCUWwtTLaLJWgZ58dGuf35xvbTa5GJiiXQTUrvmNdWBYWqRm7j3fyrRWk9UBYKimgCBStPse_XcsYI1km7mEDIjIYwzE9Ji6i0Uk9Bi8bwuUDNZoDh70mczWrGEgZcdvYQAfFNIhAvQCXar7Sae3JWnwsg8',
    thumbnailImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD61lJ97QUvcfM6zPiGesVKomlY_eqe4yFFZFjQpSLJ0O1zdmEU82AfOLexXT9FVjM3VPK3aWrn2UgCpD42zhSeBoviEDBllwlRJAzPf5vnPvgCQ7PccCUWwtTLaLJWgZ58dGuf35xvbTa5GJiiXQTUrvmNdWBYWqRm7j3fyrRWk9UBYKimgCBStPse_XcsYI1km7mEDIjIYwzE9Ji6i0Uk9Bi8bwuUDNZoDh70mczWrGEgZcdvYQAfFNIhAvQCXar7Sae3JWnwsg8',
    urgent: false,
    coords: { x: 28, y: 15, name: 'Chiang Mai' }
  }
];

export const PETS: Pet[] = [
  {
    id: 'thong',
    name: 'เจ้าทอง',
    age: '2 ปี',
    sex: 'male',
    breed: 'Thai Mix',
    tags: ['ร่าเริง', 'เข้ากับเด็กได้', 'เป็นมิตร'],
    location: 'Bangkok',
    mainImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAaCYMlSFshRanngxZ520Pa07G5A2k8qo2AxcjAZwN4V4H92zX_Px8922yyUJOdc3l7yLu7ZmCd1xRDj2jOklcElF923A3Kws9MJa07qsL4TUVWeVDqHJiIjkNX_1_I-nrAPZkWaBnTaBUZJ_cnXiN_HRZ8AseAyfesaplUt7S9bR5QnJ8Sr4peaIKwd4sO6TgxvbQqOAVz9OsYH7DgCp00-ei3GTxoHtJlXeCzUWw8l3HFcAhl09vy0ZBnF7_zjMSn2vQ95nFNEDw',
    about: '"น้องถูกพบที่ข้างถนน ตอนนี้รักษาสุขภาพแข็งแรงแล้ว รอพี่ใจดีมารับไปดูแลครับ"',
    longAbout: 'Thong is a very sweet boy who loves to play catch. Despite a tough start on the streets of Bangkok, he has boundless energy and affection. He is fully vaccinated and neutered.',
    vaccinated: true,
    neutered: true,
    houseTrained: true,
    goodWithKids: true,
    category: 'dogs',
    foundationId: 'paws-bangkok'
  },
  {
    id: 'milo',
    name: 'Milo',
    age: '3 Months',
    sex: 'male',
    breed: 'Mixed Breed',
    tags: ['Puppy', 'ขี้เล่น', 'พลังงานสูง'],
    location: 'Chiang Mai',
    mainImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBqydIXs6jRm9P3OzyzQS24892e5NkzjSlkFhH4-AZH9sUkf5lSU5GUCq-wE_oZY-3XNgLHuBoXfjS_8OISNfDJrOO2lFbZktVGkcWkUC52OSwj_9uGSejPky4VVQy98wVsBpaYySRlJccIDR1ugsM780U6TNgoNrB2ojf8tsLWtscMJ6ldxSXmOw-j-Aw5gRWU1fuoZAn96OzxauvjK04N-wbbWpAhnkQr_w3deKTU7AtOj1QiIaNR9Hx1ivvjIhII5F2WO-tNBl8',
    about: '"ลูกหมาเพศผู้สุดซน ถูกช่วยเหลือจากไซต์งานก่อสร้าง กำลังมองหาบ้านที่รักน้องจริงครับ"',
    longAbout: 'Milo is an adorable, high-energy puppy who was rescued from a construction site. He is incredibly playful, loves other dogs, and is eager to learn new tricks.',
    vaccinated: true,
    neutered: false,
    houseTrained: false,
    goodWithKids: true,
    category: 'dogs',
    foundationId: 'happy-tails-haven'
  },
  {
    id: 'bella',
    name: 'Bella',
    age: '8 Years',
    sex: 'female',
    breed: 'Retriever Mix',
    tags: ['Senior', 'ใจเย็น', 'รักสงบ'],
    location: 'Chiang Mai',
    mainImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB2OGLEvLZbwIbkGKxXXYRqHMI2eyGkF5_ywYpKX8FgipWu_A5jZC-AfA67lCUpaFSW1xNGQD3NanwgfxHB_BzLR3ifNdMjuqJX5FEJagsNWax9Se7yA-zE3sxqvgXpyWFGRkpRLy_-74bnNybH_AZHYa4DkFsbtevY-FyAC7KjACRm-Qb5FLl2X5j--wqxtMuvLyzKjkIXiQU42o1kDjLQmP9uqpBiAzDlv8ac8YYKHVNkyTqRX7rP31sebwAmXaB9s8d8Qt3qLzY',
    about: '"สุนัขโกลเดนรีทรีฟเวอร์สูงวัย อ่อนโยน รักความสงบ เหมาะสำหรับบ้านที่ชอบความเงียบสบาย"',
    longAbout: 'Bella is a gentle senior golden retriever mix who loves warm blankets, slow walks, and being a quiet companion. She is house trained and great with kids.',
    vaccinated: true,
    neutered: true,
    houseTrained: true,
    goodWithKids: true,
    category: 'dogs',
    foundationId: 'happy-tails-haven'
  },
  {
    id: 'thongdee',
    name: 'ลุงทองดี',
    age: '8 ปี',
    sex: 'male',
    breed: 'Golden Retriever Mix',
    tags: ['ใจเย็น', 'เรียบร้อย', 'รักสงบ'],
    location: 'Chiang Mai',
    mainImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBsil4GNiDmciJ9OJ4x5aksamlA6hEyb6N6hET2dq4Eaqwc6-YTnnVSOYEQcYQMF_tas1DMj-U8TswK_i6BAcx7aeGDvAsr5q0BuoTdM9qxHYUeNTQHCb8t05JiEGlrbUWpvm2f_F_ou0-15WxWnxB76-vekV9g-dw_Roi4cyI3bEYfdBit2M9AwvmRwmQ1j7DZZwIYqcxkYvTgeawgU5PnVWLnkqWIT-HvP_pO1hFBwQGDo9ZKhJNhN5xgjV674eBTBBZ72GSnr7c',
    about: '"สุนัขโกลเดนวัยเก๋า อารมณ์ดี อ่อนโยน เข้ากับคนง่ายมาก รักสงบและชอบนอนข้างๆ เจ้าของ"',
    longAbout: 'Thongdee is a lovely, mature dog who excels at relaxing and providing emotional support. Perfect match for a cozy indoor lifestyle.',
    vaccinated: true,
    neutered: true,
    houseTrained: true,
    goodWithKids: true,
    category: 'dogs',
    foundationId: 'soi-dog-foundation'
  },
  {
    id: 'kanomphing',
    name: 'ขนมผิง',
    age: '3 ปี',
    sex: 'female',
    breed: 'Pomeranian Mix',
    tags: ['ขี้อ้อน', 'ขี้เล่น', 'ร่าเริง'],
    location: 'Bangkok',
    mainImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC6DVMU7HyiIG1i58r8imA1gPWPV5I3pV3M7oA3ro4LauBgJartdalr0IaCv4avJr3wDXsZYR2ud6LcWSTv1JjcQJsVuyWoau8pSzhlPsj-HaLyaviA5OYKzyqMcUohkXB3spS6HkMV1UpEZUpQlTYzkjdwO_6GfbxFD4mLy_fkKyZIFTbMixZjomI-5rdb2MnT1or4l4xXEOgRDDoKORD7TekQ2avGjk1yO3ZrL43cRYhVlaZMi8KnezMexdlJ08W_sz7HY4S7v3Q',
    about: '"สุนัขพันธุ์เล็ก ขนปุย ขี้อ้อนสุดๆ ชอบวิ่งเล่นในบ้านและนอนหนุนตัก ติดคนมาก"',
    longAbout: 'Kanomphing is a gorgeous fluffy companion who brings joy to any apartment. She loves affection and gets along with everyone.',
    vaccinated: true,
    neutered: true,
    houseTrained: true,
    goodWithKids: true,
    category: 'dogs',
    foundationId: 'paws-bangkok'
  },
  {
    id: 'chanom',
    name: 'ชานม',
    age: '5 ปี',
    sex: 'female',
    breed: 'Thai Mix',
    tags: ['เรียบร้อย', 'เป็นมิตร', 'รักสะอาด'],
    location: 'Nonthaburi',
    mainImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBFeOsaopKesFJ-jOh1ymw_Hmesf0RVy5g3M_zB4Y5jQzGPfz7L8HSLrOJAnmgwTdtLBVMh20bq1TahrcSx5T7sBi6lOFr48kuhXJiLs6Ry0d5pWBovTf7z3Eluri6-LFmPxP6oHryg2cOmf-sSC92ps8Tm8T0n7HhLJM5cP3LemOqJtwfv9BwRzIfD01uTbwWu04C_XI2adMsh1nIZbbPGEBEIzp08v7lV_wOUE8u8QeqWu3eJxB3lmOQMMZIBps4ueHO2A7P6xCY',
    about: '"น้องหมาเรียบร้อย รักสงบ มีโลกส่วนตัวบ้างแต่เข้าหาคนแปลกหน้าได้อย่างอ่อนโยน สุขภาพแข็งแรง"',
    longAbout: 'Cha-nom is an independent, clean, and perfectly quiet dog. She loves cozy corners and watching the world go by.',
    vaccinated: true,
    neutered: true,
    houseTrained: true,
    goodWithKids: true,
    category: 'dogs',
    foundationId: 'paws-bangkok'
  },
  {
    id: 'khaitun',
    name: 'ไข่ตุ๋น',
    age: '1 ปี',
    sex: 'male',
    breed: 'Siamese Mix',
    tags: ['ซนมาก', 'ชวนคุยเก่ง', 'ขี้อ้อน'],
    location: 'Bangkok',
    mainImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCxJPSJEtHBfq6qZPDd8EE1BJwysQ7qT8b_JlJNnVOUoqB0RJ8VglshvpWznnOm1YMj7GPXsrRAz_kfNSvDQR3E781THATYGB0gLjDCm4p16aAQg85bNK90ieU6HyO0OJDUGf4UOiiEXXH99YMsFIW_-qWwHxaqzgftBbGvc3dOAeVmI1Ga7v6NErPpHD_kclKoGQNZEoTGqaZLUPe1quto9U8Cswk-EOvZ_JVzKrhKj6qhOebjVGhv99Fat1b1f1OoyOAbqy3G_YQ',
    about: '"น้องแมวสามสีผสมวิเชียรมาศ ร้องทักเก่งมาก ทานง่าย ขี้เล่น แข็งแรงสมบูรณ์"',
    longAbout: 'Khaitun is highly interactive, chatty, and loves playing with simple cat toys. Fully vaccinated and litter trained.',
    vaccinated: true,
    neutered: true,
    houseTrained: true,
    goodWithKids: true,
    category: 'cats',
    foundationId: 'paws-bangkok'
  },
  {
    id: 'plai-somboon',
    name: 'พลายสมบูรณ์',
    age: '15 Years',
    sex: 'male',
    breed: 'Asian Elephant',
    tags: ['อ่อนโยน', 'ขี้เล่น', 'รักธรรมชาติ'],
    location: 'Chiang Mai',
    mainImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDXN5934uOj7D7OjTCE9JUEOU9lp1BFusOnUmA-kLFBhYFr1l2vWDJ04sjFr1wsi575OXJfVzwqtZmtAUzC73PwItYCKy4TWdcShP6fPohadV3vylgKOQqAoZuZ-8WztF9I6d6_L2m28qh-326fMqpC68HKZp1MYrFEIRSt9X6-ISwyLMrJ2J2ZiV9Rk6KAus0_OW1V0JjpjvfF7fsDIduxTHmUjakO-zo3wVydqgKQMZVnHiynRmwfSrWQuEE00ANoXmBWEoZraJc',
    about: '"อดีตช้างลากซุง ตอนนี้ได้ใช้ชีวิตอิสระ แช่โคลนและเดินป่าในธรรมชาติเชียงใหม่อย่างสุขสมบูรณ์ครับ"',
    longAbout: 'Plai Somboon is a magnificent rescued elephant enjoying life in his cage-free reserve. You can sponsor his daily diet of pineapples, sugarcane, and bananas!',
    vaccinated: true,
    neutered: false,
    houseTrained: false,
    goodWithKids: true,
    category: 'wildlife',
    foundationId: 'elephant-nature-park'
  }
];

export const GALLERY_IMAGES = [
  'https://lh3.googleusercontent.com/aida-public/AB6AXuAF9kr10i-opD5ZkuZR-AVrZkscbINECquOPatY1nF5wVb8E4HlUUFGFFlk9er7zgVD3GouSLvPT7dYMW7QS6urfHO6Jaa84KhHeob56PnP_ijSt9CPk5mPClg1qvGtjAK-QppeF9DoUwo2RVMn53VIEOLdYw7gEFppKolR2TOMz0AynWRXZxzWihjPxmtG5jupkuAVBYs9dzMByGBPXZ6aBm4cCHJhSzBE1Fxhzp1WQmzxUdYy53G2FTV_Ql_nP18Q6El22glbJOw',
  'https://lh3.googleusercontent.com/aida-public/AB6AXuC4vc9jr1B5BIuYV7g2AxjZjx4EyMVlVlbKrHVuhyYrtonSuTAzlHOAM3C9IRXHx51Odtec9JwJjhomtsKYoO1v10VSm0FSzNuZvD5EubO252ioj_ctuUFnc0eKVHvL4HzP0oA0o6K0k84xVNsvHGtZzdS8PI6piYO88JjGCdJoodltf1nvetQgPZulBWzK7-AQfUcdMlQYxTn-iRQDWzKVO3xKbKIL4uK2bHHGXtjCflZicahSms7zpEkZJyRtN2qH2l83RA1SvzY',
  'https://lh3.googleusercontent.com/aida-public/AB6AXuCFeLwTI30oB_YQMkCgr5UCtaMlkIy25me_mLIGJOlHek-6Ie16lmLluX8EgNKlXRkWGZNUeLGBx17mk2Jv3eGP7DE1mLw2RfiOl8cuYbFlU2t6qpmwRY6eWBRnN_3C04gtE26Y3TpKmaECAPHCWqMF9jjvm_hl9D9-NNJC_2hpGyibdHWK4p_aIMahjt4MhOxNri88CtozbHt025XW1tdOD6l2fk94Ct4HZOrRiOPh1nQuTCFDnAgtzHrpQh-gaoQfdqdqJKYLeMs'
];
